In [1]:
import pandas as pd

# Load datasets Fall 2021 - Spring 2022
LearnerPostSurvey = pd.read_excel("Spring2022_LearnerPostSurvey_Scrubbed.xlsx")
LearnerPreSurvey = pd.read_excel("Spring2022_LearnerPreSurvey_Scrubbed.xlsx")
LearnerRegistration = pd.read_excel("Spring2022_LearnerRegistration_Scrubbed.xlsx")
LearnerRoster = pd.read_excel("Spring2022_LearnerRoster_Scrubbed.xlsx")

In [2]:
# Lets see the size of the datasets
print("LearnerPostSurvey: ", LearnerPostSurvey.shape)
print("LearnerPreSurvey: ", LearnerPreSurvey.shape)
print("LearnerRegistration: ", LearnerRegistration.shape)
print("LearnerRoster: ", LearnerRoster.shape)

LearnerPostSurvey:  (22, 53)
LearnerPreSurvey:  (42, 52)
LearnerRegistration:  (44, 13)
LearnerRoster:  (42, 24)

In [3]:
LearnerRegistration.head(3)

,ID,Full_name,Participant's First Name,Participant's Last Name,What pronouns does your student prefer? - Selected Choice,Student Age,Grade level,How would your student describe their racial identity?,Student Language Preferences,School,Please select which team your child would like to join for the 8 week program,How did you hear about Ignite? - Selected Choice,Acceptance Letter (Y/N)
0,44,AaronAckner,Aaron,Ackner,he/him/his,12,6th,Asian,English,Rogers Herr Year Round Middle School,Water,Other,Y
1,46,AddisonHodge,Addison,Hodge,She/her/hers,13,8th,Black,English,The School for Creative Studies,Health,"Duke University GWHT Email,Other",Y
2,45,AddisonDiener,Addison,Diener,She/her/hers,14,8th,White,English,Ravenscroft,Health,Email from the Museum of Life and Science,Y

In [4]:
LearnerRoster.head(3)

,ID,Full_Name,Season,First Name,Last Name,Course,Pre- Survey,Wk 1,Wk1 Style,Wk 2,...,Wk 7,Wk 8,Post- Survey,Poster: Conceptual,Poster: Functionality,Poster: Aesthetic,Poster: Testing,Poster:Community,Poster: Poster,Rubric total
0,44,AaronAckner,Spring2022,Aaron,Ackner,Water,X,X,Zoom,X,...,Absent,Absent,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,45,AddisonDiener,Spring2022,Addison,Diener,Health,x,X,Zoom,X,...,x,x,X,10.0,10.0,10.0,10.0,10.0,10.0,60.0
2,46,AddisonHodge,Spring2022,Addison,Hodge,Water,x,X,Zoom,X,...,Absent,Absent,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
# Merge LearnerRegistration with LearnerRoster
LearnerRegistration_merged = pd.merge(
    LearnerRegistration, LearnerRoster, on="ID", how="left"
)

# Check the size of the original datasets
print("LearnerRegistration: ", LearnerRegistration.shape)
print("LearnerRoster: ", LearnerRoster.shape)

# Check the size of the merged dataset
print("LearnerRegistration_merged: ", LearnerRegistration_merged.shape)

LearnerRegistration:  (44, 13)
LearnerRoster:  (42, 24)
LearnerRegistration_merged:  (44, 36)

In [6]:
LearnerRegistration_merged.head(3)

,ID,Full_name,Participant's First Name,Participant's Last Name,What pronouns does your student prefer? - Selected Choice,Student Age,Grade level,How would your student describe their racial identity?,Student Language Preferences,School,...,Wk 7,Wk 8,Post- Survey,Poster: Conceptual,Poster: Functionality,Poster: Aesthetic,Poster: Testing,Poster:Community,Poster: Poster,Rubric total
0,44,AaronAckner,Aaron,Ackner,he/him/his,12,6th,Asian,English,Rogers Herr Year Round Middle School,...,Absent,Absent,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,46,AddisonHodge,Addison,Hodge,She/her/hers,13,8th,Black,English,The School for Creative Studies,...,Absent,Absent,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,45,AddisonDiener,Addison,Diener,She/her/hers,14,8th,White,English,Ravenscroft,...,x,x,X,10.0,10.0,10.0,10.0,10.0,10.0,60.0

In [7]:
# Check the size of the original datasets
print("LearnerRegistration_merged: ", LearnerRegistration_merged.shape)
print("LearnerPreSurvey: ", LearnerPreSurvey.shape)

# Merge LearnerRegistration_merged with LearnerPreSurvey, right on Participant
LearnerRegistration_merged = pd.merge(
    LearnerRegistration_merged, LearnerPreSurvey, on="ID", how="left"
)

# Size after the merge
print("LearnerRegistration_merged: ", LearnerRegistration_merged.shape)

LearnerRegistration_merged:  (44, 36)
LearnerPreSurvey:  (42, 52)
LearnerRegistration_merged:  (44, 87)

In [9]:
#LearnerRegistration_merged.head(3)

In [10]:
# Download the merged dataset to a csv file
LearnerRegistration_merged.to_csv("LearnerRegistration_Year1_2021_2022.csv", index=False)