In [1]:
import pandas as pd

In [2]:
# Load datasets Learners Spring 2023
LearnerPostSurvey2023 = pd.read_excel("Spring2023_LearnerPostSurveyAll_Scrubbed.xlsx")
LearnerPreSurveyAll2023 = pd.read_excel("Spring2023_LearnerPreSurveyAll_Scrubbed.xlsx")
LearnerRegistration2023 = pd.read_excel("Spring2023_LearnerRegistration_Scrubbed.xlsx")
LearnerRoster_Scrubbed2023 = pd.read_excel("Spring2023_LearnerRoster_Scrubbed.xlsx")

In [3]:
# Lets see the size of the datasets
print(LearnerPostSurvey2023.shape)
print(LearnerPreSurveyAll2023.shape)
print(LearnerRegistration2023.shape)
print(LearnerRoster_Scrubbed2023.shape)

(47, 57)
(56, 57)
(53, 15)
(64, 23)

In [4]:
LearnerRegistration2023.head(3)

,ID,Full_Name,StudentFirstName,StudentLastName,What pronouns does your student prefer? - Selected Choice,Student Age,Grade level,How would your student describe their racial identity?,Student Language Preferences,School,City,Zip Code,Please select which team your child would like to join for the 8 week program,How did you hear about Ignite? - Selected Choice,Accepetance Letter (Y/N)
0,124,AanyaPrashanth,Aanya,Prashanth,She/her/hers,14,8th,Other,English,West Cary Middle,Cary,27519,Health,previous Ignite participant,Y
1,102,AayushChayan,Aayush,Chayan,he/him/his,12,7th,Asian,English,Lakewood Montessori Middle School,Durham,27713,Light,School email,Y
2,130,AlaynaSmith,Alayna,Smith,She/her/hers,11,6th,White,English,Rogers-Herr Middle,Durham,27707,Health,Email,Y

In [5]:
LearnerRoster_Scrubbed2023.head(3)

,ID,Full_Name,Season2023,First Name,Last Name,Course,Pre- Survey,Wk 1,Wk 2,Wk 3,...,Wk 7,Wk 8,Post- Survey,Poster: Conceptual,Poster: Functionality,Poster: Aesthetic,Poster: Testing,Poster:Community,Poster: Poster,Rubric total
0,124,AanyaPrashanth,Spring2023,Aanya,Prashanth,Health,X,X,X,X,...,X,X,x,10.0,10.0,10.0,5.0,0.0,10.0,45.0
1,NC,AaronStinehour,Spring2023,Aaron,Stinehour,Light,No,Ab,Absent,Absent,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NC,AaronAustin,Spring2023,Aaron,Austin,Health,No,withdrew,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
# Merge LearnerRegistration with LearnerRoster
LearnerRegistration_merged = pd.merge(
    LearnerRegistration2023, LearnerRoster_Scrubbed2023, on="ID", how="left"
)

# Check the size of the original datasets
print("LearnerRegistration: ", LearnerRegistration2023.shape)
print("LearnerRoster: ", LearnerRoster_Scrubbed2023.shape)

# Check the size of the merged dataset
print("LearnerRegistration_merged: ", LearnerRegistration_merged.shape)

LearnerRegistration:  (53, 15)
LearnerRoster:  (64, 23)
LearnerRegistration_merged:  (53, 37)

In [7]:
LearnerRegistration_merged.head(3)

,ID,Full_Name_x,StudentFirstName,StudentLastName,What pronouns does your student prefer? - Selected Choice,Student Age,Grade level,How would your student describe their racial identity?,Student Language Preferences,School,...,Wk 7,Wk 8,Post- Survey,Poster: Conceptual,Poster: Functionality,Poster: Aesthetic,Poster: Testing,Poster:Community,Poster: Poster,Rubric total
0,124,AanyaPrashanth,Aanya,Prashanth,She/her/hers,14,8th,Other,English,West Cary Middle,...,X,X,x,10.0,10.0,10.0,5.0,0.0,10.0,45.0
1,102,AayushChayan,Aayush,Chayan,he/him/his,12,7th,Asian,English,Lakewood Montessori Middle School,...,Absent,Absent,NO,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,130,AlaynaSmith,Alayna,Smith,She/her/hers,11,6th,White,English,Rogers-Herr Middle,...,Absent,X,x,10.0,10.0,5.0,5.0,5.0,10.0,45.0

In [8]:
# Check the size of the original datasets
print("LearnerRegistration_merged: ", LearnerRegistration_merged.shape)
print("LearnerPreSurvey: ", LearnerPreSurveyAll2023.shape)

# Merge LearnerRegistration_merged with LearnerPreSurvey, right on Participant
LearnerRegistration_merged = pd.merge(
    LearnerRegistration_merged, LearnerPreSurveyAll2023, on="ID", how="left"
)

# Size after the merge
print("LearnerRegistration_merged: ", LearnerRegistration_merged.shape)

LearnerRegistration_merged:  (53, 37)
LearnerPreSurvey:  (56, 57)
LearnerRegistration_merged:  (53, 93)

In [11]:
# Check the size of the original datasets
print("LearnerRegistration_merged: ", LearnerRegistration_merged.shape)
print("LearnerPostSurvey: ", LearnerPostSurvey2023.shape)

# Merge LearnerRegistration_merged with LearnerPostSurvey, right on Participant
LearnerRegistration_merged = pd.merge(
    LearnerRegistration_merged, LearnerPostSurvey2023, on="ID", how="left",suffixes=('_left', '_right')
)

# Size after the merge
#print("LearnerRegistration_merged: ", LearnerRegistration_merged.shape)

LearnerRegistration_merged:  (53, 93)
LearnerPostSurvey:  (47, 57)

In [12]:
# Download the merged dataset to a csv file
LearnerRegistration_merged.to_csv(
    "LearnerRegistration_Year2_2022_2023.csv", index=False
)